### ISSUE TITLE
Can't find klyng in path

### ISSUE THREAD

**Issue by OutsourcedGuru** [Mostafa-Samir/klyng#1]
I took your advice in the installation instructions and created a `~/.npm-modules` folder and ran the `NPM_CONFIG_PREFIX=/home/pi/.npm-modules npm install -g klyng` as root and edited the `~/.profile` file to prepend `~/.npm-modules/bin` to the PATH.

1. `echo $PATH` shows that it's correctly prepending the bin folder that includes the symlink.
2. `which klyng` shows `/home/pi/.npm-modules/bin/klyng` as expected.
3. The `klyng` symlink points to `~/.npm-modules/lib/klyng/bin/main.js`.
4. There appears to be a problem when attempting to run this on OS X or any Linux-based computer in that the top line of `main.js` ends in a CR+LF ("\r\n") pairing rather than just the expected new line which is typical for Linux.  I'm guessing that you edit your files in Windows.
5. As a result of this, `bash` can't properly figure out which `node` command that you're trying to run from the top line of your `main.js` file.  It sees "node\r" and looks for this throughout the PATH and doesn't see it.  The end result is `-bash: /usr/bin/klyng: No such file or directory`.

If you use `vi` to edit `main.js` in-place and remove the "\r" at the end of the first line, it can at least attempt to proceed.  Doing this will then find `klyng` where it lives.

**Comment by Mostafa-Samir** [comment]
Good catch! Thanks!
It's fixed now.

Feel free to reopen the issue if the problem persists.
