### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by OutsourcedGuru** [Mostafa-Samir/klyng#2]
Node:  v7.3.0
O/S: (Raspian) Linux _computername_ 4.4.38-v7+ #938 SMP Thu Dec 15 15:22:21 GMT 2016 armv7l GNU/Linux
...and also 
O/S: (Mac OS X El Capitan) Darwin _computername_ 15.6.0 Darwin Kernel Version 15.6.0: Wed Nov  2 20:30:56 PDT 2016; root:xnu-3248.60.11.1.2~2/RELEASE_X86_64 x86_64
Klyng: 1.0.2

Installed globally per instructions.  Created project with npm and then did a `npm install --save klyng`.

Attempting to run any command beginning with `klyng ...` results in an **UnhandledPromiseRejectionWarning**.

For example, `klyng --beacon-up`:
```
(node:3339) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: ipc.of.klyng_beacon.on is not a function
(node:3339) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
/home/pi/.npm-modules/lib/node_modules/klyng/node_modules/node-ipc/dao/client.js:125
            client.trigger('error', err);
                   ^

TypeError: client.trigger is not a function
    at Socket.<anonymous> (/home/pi/.npm-modules/lib/node_modules/klyng/node_modules/node-ipc/dao/client.js:125:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1281:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

Or `klyng -n 1 hello.js`:
```
(node:3357) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: ipc.of.klyng_beacon.on is not a function
(node:3357) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
/home/pi/.npm-modules/lib/node_modules/klyng/node_modules/node-ipc/dao/client.js:125
            client.trigger('error', err);
                   ^

TypeError: client.trigger is not a function
    at Socket.<anonymous> (/home/pi/.npm-modules/lib/node_modules/klyng/node_modules/node-ipc/dao/client.js:125:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1281:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

...yields the exact same error.

Trying `sudo klyng --beacon-up` yields `sudo: klyng: command not found`.
Trying `sudo /home/pi/.npm-modules/bin/klyng --beacon-up` yields the same result in the first two examples, so I don't think it has to do with rights.

I'd really like to use your code if I can.  See [e=mc2](https://github.com/OutsourcedGuru/e-mc2) supercomputer project.

**Comment by Mostafa-Samir** [comment]
Thank you for reporting this. 

It was a dependency issue: when I created klyng, the module I used for IPCs (node-ipc) had some bugs in it. I fixed them back then and created the pull requests but it took the maintainer so long to merge them. So to release klyng, I installed the dependency directly from my fork which contains the fixes and forgot to change back to the original repo after my fixes were merged. So when one of node-ipc dependencies changed, and the code in my fork remained still without accounting for such changes, everything broke!

Now that node-ipc is installed directly from its original repo, the issue you reported should be fixed.

Feel free to reopen the issue if the problem persists.

**Comment by OutsourcedGuru** [comment]
Brilliant, dude.  It now works great.  I think I had to do something interesting to install it...

```
$ mkdir ~/.npm-modules
$ echo export PATH=\~/.npm-modules/bin:\$PATH >> ~/.profile
$ source ~/.profile
$ NPM_CONFIG_PREFIX=/home/pi/.npm-modules sudo npm install -g klyng
```

Didn't seem to work out.  So I then proceeded with...

```
$ sudo npm uninstall -g klyng
$ sudo bash
#   Note that we're now logged in as root and the
#   prompt has changed to root@gru:/home/pi# so
#   just copy/run everything after the prompt.
root@gru:/home/pi# NPM_CONFIG_PREFIX=/home/pi/.npm-modules npm install -g klyng
root@gru:/home/pi# exit
```

And that seems to work as expected.  The supercomputer is now working with the Hello, Minions! JavaScript using your module.  [Here is that subset of the instructions.](https://github.com/OutsourcedGuru/e-mc2/tree/master/demo/01-hello)

**Comment by OutsourcedGuru** [comment]
What's interesting is that each remote node needs to run `sudo klyng...` and the master seems to get away with just running `klyng...`.  Not sure if this is my setup or what but you might mention this to your own users in your documentation.

**Comment by OutsourcedGuru** [comment]
Oh... and I seem to recall that the remote nodes failed with a message that they couldn't create the `.unpacks` folder.  I think I then manually created it for them and they were then able to proceed.  Or... I `chmod`'d the parent folder perhaps to the user's name and group.

You might just create an empty .unpacks folder within your image and avoid the whole issue.

**Comment by Mostafa-Samir** [comment]
I'm glad that its working with you!

When you installed it on remote nodes, did you use the same process of creating a different global dir intead of the one in root or just used `sudo npm install -g klyng`? if you used the latter and didn't fire up the beacon with `sudo` then this problem is expected! because `.unpacks` then would reside under a root path!

Anyway I'm glad that the framework is being used, I've wanted to add more directives for collective communication (like `gather`, `scatter` and `reduce`) and wasn't really motivated to do that, perhaps I can get around and do that soon!

**Comment by OutsourcedGuru** [comment]
Pretty sure the install was identical throughout.

I'm giving a talk this Tuesday on "Supercomputing in JavaScript" at [SanDiego.js](https://www.meetup.com/sandiegojs/events/236195576/) in front of maybe a hundred people so you may get some recognition and/or traffic to your repository (possibly).

What's funny is that if I attempt to move the master's website* to run as root then I have to explicitly give the path to the `klyng` executable for it to be found... and then it ultimately doesn't work when submitting jobs after that.  I'll have to play around with all that later--I think I'd like all the nodes to be at the same level (user versus root) simply for consistency.  I'll figure it out, though.

* Note that the website does server-side to run the `klyng --beacon-up`, for example.

**Comment by OutsourcedGuru** [comment]
Was able to introduce your library to a group of 155 at the SanDiego.js meeting last night to much applause.  Thanks, again.
